### ISSUE TITLE
TypeError: work() got an unexpected keyword argument 'logging_level'

### ISSUE THREAD

**Issue by bemcdonnell** [michaelbrooks/rq-win#3]
Hey All! nice project.  I'm having an issue running this. 

`rqworker -w rq_win.WindowsWorker`

I'm running Py27-32bit
Windows10

```
PS C:\Users\Bryant> rqworker -w rq_win.WindowsWorker
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\rqworker.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\rq\cli\cli.py", line 73, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\rq\cli\cli.py", line 232, in worker
    worker.work(burst=burst, logging_level=logging_level)
TypeError: work() got an unexpected keyword argument 'logging_level'
```

**Comment by michaelbrooks** [comment]
I'm guessing that the `rq` package made a breaking change in the worker API. `rq-win` must be updated to work with newer versions of RQ. I'm not able to take the on at the moment. You can either take a look at the code here and compare it to the original `Worker` class [here](https://github.com/rq/rq/blob/master/rq/worker.py), or you can downgrade to a version of rq closer to 0.3.13 (which is where it was when I wrote this package originally).

**Comment by bemcdonnell** [comment]
@michaelbrooks, no worries. I'll see what I can do.. and if get it working, i'll PR back!

**Comment by andrewvaughanj** [comment]
@bemcdonnell this should be fixed in [PR5](https://github.com/michaelbrooks/rq-win/pull/5).
