### ISSUE TITLE
Using Win_worker with Flask context

### ISSUE THREAD

**Issue by kc1** [michaelbrooks/rq-win#4]

**Comment by kc1** [comment]
I'm trying to extend the flask-base project https://github.com/hack4impact/flask-base/tree/master/app which can use RQ. I came across https://github.com/michaelbrooks/rq-win . I love the idea of this repo (If I can get it working it will really simplify my life, since I develop on win 10 -64):

 After installing this library I changed the code in manage.py to:


    from rq_win import WindowsWorker

    @manager.command
    def run_worker():
        """Initializes a slim rq task queue."""
        listen = ['default']
        conn = Redis(
            host=app.config['RQ_DEFAULT_HOST'],
            port=app.config['RQ_DEFAULT_PORT'],
            db=0,
            password=app.config['RQ_DEFAULT_PASSWORD'])
    
        with Connection(conn):
            # worker = Worker(map(Queue, listen))
            worker = WindowsWorker(map(Queue, listen))
            worker.work()

When I try to run it with:

    $ python -u manage.py run_worker 

it appears to start normally with no errors. I can queue a job in my views by running something like:

         @login_required
         @main.route('/selected')
         def selected():
         messages = 'abcde'
          j = get_queue().enqueue(render_png, messages, result_ttl=5000)
          return j.get_id()

This returns a job_code correctly. However trying:

    @main.route("/jobs", methods=['GET'])
    def get_jobs():
        return str(get_queue().job_ids)

gives:

    []

I'm suspecting that the WindowsWorker class is not interfacing properly with the remainder of the task queue. Do you have any thoughts on how to get this working?

**Comment by michaelbrooks** [comment]
Looking at the source code for the worker class built in to rq (https://github.com/rq/rq/blob/master/rq/worker.py), it seems the interface for workers has changed substantially. I last tested this with rq v0.3, and it is now on 0.10. I suggest you try downgrading your rq library to see if that helps. Alternatively, it may be possible to upgrade this extension to support the new library.

**Comment by kc1** [comment]
Michael, I'm not an expert python programmer, but if you have any insights on how to approach this I'd be willing to play with it . Meanwhile I will try to downgrade to rq 0.3

**Comment by kc1** [comment]
Downgraded to rq 0.3.13:

    $ rqworker -w rq_win.WindowsWorker
    15:33:17 Using rq_win.WindowsWorker (experimental)
    15:33:17 RQ worker started, version 0.3.13
    15:33:17
    15:33:17 *** Listening on ?[32m?[39;49;00m...
    15:33:51 ?[32mdefault?[39;49;00m: ?[34mapp.main.views.render_png('{MY ARGUMENTS}', result_ttl=5000)?[39;49;00m (21dc12d8-0c96-459c-9025-ee3ff74e0429)
    Traceback (most recent call last):
      File "...\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "...\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "...\Scripts\rqworker.exe\__main__.py", line 9, in <module>
      File "...\lib\site-packages\rq\scripts\rqworker.py", line 90, in main
        w.work(burst=args.burst)
      File "...\lib\site-packages\rq_win\worker.py", line 42, in work
        return super(WindowsWorker, self).work(burst)
      File "...\lib\site-packages\rq\worker.py", line 326, in work
        self.fork_and_perform_job(job)
      File "...\lib\site-packages\rq\worker.py", line 373, in fork_and_perform_job
        child_pid = os.fork()
    AttributeError: module 'os' has no attribute 'fork'

**Comment by michaelbrooks** [comment]
Hmm I'm not sure why downgrading didn't work. `os.fork` is only available on unix systems, not on Windows. The point of the rq-win extension was to avoid having to call os.fork.

**Comment by kc1** [comment]
Hi Stephen,

Thanks for looking at this. Attached is a stripped down version of what I have so far.

You can login to the flask-app with

test1@test.com
12345678

I'm running the worker through the manage.py file using git bash

$ python -u manage.py run_worker 

I appreciate you taking a quick look if you have time.

https://drive.google.com/file/d/1pGq_BhYmTi2z4UYvhDrfF6nL-cb7g3Mj/view

**Comment by andrewvaughanj** [comment]
@kc1 I just opened-up [PR5](https://github.com/michaelbrooks/rq-win/pull/5), which hopefully might resolve this for you (at least, I had very similar issues as you were facing, and things now work for me)!
