### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'exists'

### ISSUE THREAD

**Issue by jaylcm** [michaelbrooks/rq-win#6]
using command rqworker -w rq_win.WindowsWorker

got this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\xxxxx\rq-win-master\rq_win\worker.py", line 49, in work
    log_format=log_format,
  File "D:\xxxxx\lib\site-packages\rq\worker.py", line 450, in work
    self.register_birth()
  File "D:\xxxxx\lib\site-packages\rq\worker.py", line 255, in register_birth
    if self.connection.exists(self.key) and \
AttributeError: 'NoneType' object has no attribute 'exists'

**Comment by jaylcm** [comment]
hi i resolve by adding 'max_jobs' argument in work pass in to super

**Comment by davidmurray** [comment]
For anyone running into this issue: my pull request (#7) fixes this. You can use [my fork](github.com/davidmurray/rq-win) until it gets merged in.
