### ISSUE TITLE
TypeError after update of rq version

### ISSUE THREAD

**Issue by jonaskluger** [michaelbrooks/rq-win#9]
Just updated to **rq 1.8.1** and it breaks the existing code with **rq-win 0.3.13**

```
14:07:38 Worker rq:worker:71361fc330ca4049b360f751732c4f9e: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "C:\das-element\venv\lib\site-packages\rq\worker.py", line 595, in work
    self.execute_job(job, queue)
  File "C:\das-element\venv\lib\site-packages\rq_win\worker.py", line 61, in execute_job
    self.main_work_horse(job, queue)
  File "C:\das-element\venv\lib\site-packages\rq_win\worker.py", line 71, in main_work_horse
    success = self.perform_job(job, queue)
  File "C:\das-element\venv\lib\site-packages\rq_win\worker.py", line 79, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
TypeError: prepare_job_execution() takes 2 positional arguments but 3 were given
```

Code did work before. Any idea whats happening?
Thanks!

**Comment by jonaskluger** [comment]
Works for **rq 1.8.0**

**Comment by michaelbrooks** [comment]
FYI @sandeepsn1997

**Comment by michaelbrooks** [comment]
Do either of you have a minimal repro of this issue? You are also welcome to submit a PR if you know the problem.

**Comment by michaelbrooks** [comment]
@jonaskluger Can you confirm if this issue is fixed for you in the latest version?

**Comment by jonaskluger** [comment]
Yes I can confirm that **rq-win 0.4.0** works for  **rq 1.9.0**
Awesome, thank you!
